#!/usr/bin/env python3

import sys


def main():
    args = sys.argv[1:]
    if len(args) != 2:
        print("Error: provide two numbers")
        sys.exit(1)
    # else:
    n1 = int(args[0])
    n2 = int(args[1])
    print(f"Sum: {n1 + n2}")


##############################################################################

if __name__ == "__main__":
    main()
